# site properties and page defaults
title: Laboratorio Sperimentale
subtitle: 
description: # Laboratorio Sperimentale's Website
IL **[Laboratorio Sperimentale](https://site.unibo.it/laboratorio-sperimentale/it)** (presso il _**Dipartimento di Lingue, Letterature e Culture Moderne**_ - **[UNIVERSITA' DI BOLOGNA](https://www.unibo.it/it)**) è un laboratorio di ricerca allestito grazie all'Iniziativa Dipartimenti di Eccellenza MIUR (L. 232 del 01/12/2016). Il Laboratorio è dotato di attrezzatura hardware e software di ultima generazione per la ricerca sperimentale, computazionale e applicata, negli ambiti della linguistica, dei translation e cultural studies, e più in generale delle Digital Humanities, anche applicate a letteratura e filologia.
Il Laboratorio inoltre organizza **[eventi formativi](https://site.unibo.it/laboratorio-sperimentale/it/agenda)** che hanno l’obiettivo di dotare di sostenere la diffusione di un know-how (inter)disciplinare teorico-pratico negli ambiti di propria competenza, promuovendo una riflessione metodologica ampia sulla diversità dei dati linguistici e testuali.
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: lilec.lab@unibo.it
  orcid: 0000-0001-8713-9213
  google-scholar: ETJoidYAAAAJ
  github: LaboratorioSperimentale
  twitter: LaboratorioSperimentale
  youtube: LaboratorioSperimentale

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
