# site properties and page defaults
title: LABORATORIO SPERIMENTALE
subtitle: Dipartimento di Lingue, Letterature e Culture Moderne
description: # Laboratorio Sperimentale's Website
header: images/orizzontale bande bianche.png
footer: images/orizzontale bande bianche.png
proofer: false

# site social media and other links
links:

  home-page: https://site.unibo.it/laboratorio-sperimentale/it/
  #orcid: 0000-0001-8713-9213
  #google-scholar: ETJoidYAAAAJ
  github: LaboratorioSperimentale
  #twitter: LaboratorioSperimentale
  #youtube: LaboratorioSperimentale
  email: lilec.lab@unibo.it

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post
  # markdown files in /seminari
  # - scope:
  #     path: "site/seminari"
  #   values:
  #     layout: seminar

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff


toc:
  min_level: 2
  max_level: 6
  ordered_list: true