- title: Composizione del TIGR
  type: blog-post
  date: 2024-04-04
  publisher: ShareTIGR
  buttons:
    - type: website
      link: https://sharetigr.usi.ch/it/news/feeds/37812

- title: Raccogliere dati linguistici ai tempi del COVID-19
  type: blog-post
  date: 2024-08-29
  publisher: ShareTIGR
  buttons:
    - type: website
      link: https://sharetigr.usi.ch/it/news/feeds/38556

- title: "Il lavoro sul campo: ricerca e contatto dei partecipanti"
  type: blog-post
  date: 2024-07-18
  publisher: ShareTIGR
  buttons:
    - type: website
      link: https://sharetigr.usi.ch/it/news/feeds/38402

- title: "Digitisation of the TIGR participant questionnaires"
  type: blog-post
  date: 2024-03-21
  publisher: ShareTIGR
  buttons:
    - type: website
      link: https://sharetigr.usi.ch/en/news/feeds/37690

- title: "Social interaction is among people. Legal, technical, and ethical explorations about personal information and its removal in talk-in-interaction as data"
  type: blog-post
  date: 2023-08-28
  publisher: CHORD talk in interaction
  buttons:
    - type: website
      link: https://www.chord-talk-in-interaction.usi.ch/news/feeds/36387

- title: "Dichiarazioni di consenso informato"
  type: blog-post
  date: 2024-07-25
  publisher: ShareTIGR
  buttons:
    - type: website
      link: https://sharetigr.usi.ch/it/news/feeds/38259

